### ISSUE TITLE
[Linux] "Click me" button hides the palette

### ISSUE THREAD

**Issue by rchastain** [RetroNick2020/raster-master#13]
Hello Nick.

Is it expected that the "click me" button hide the palette?

![clickme](https://user-images.githubusercontent.com/13957204/182298891-33cd3125-f6bd-42a4-a44e-97a35ea753af.png)

I could not find a way to select the colors hidden by the button.

Regards.

Roland

**Comment by RetroNick2020** [comment]
you can just move the blue sizing bar. Although i don't see it in the
included image. Hover around the edge of the vertical scroll bar and see
you see a sizing icon and move towards the left.

The color palette component does not respect the z-order values. It should
overlay over the RM logo. I will check to see if there is an update.

**Comment by RetroNick2020** [comment]
I had a chance to look at this in a virtual machine. I'm afraid things are not good on linux.
1. You need to increase your desktop resolution. It looks like nothing fits at 800x600
2. The splitters don't appear blue with linux/
![Capture](https://user-images.githubusercontent.com/56885781/182656708-9b1219ef-119c-4537-b567-6b22c8f21c0e.PNG)
gtk - they are just a small gray line beside the edge of the color box (to the left)
3. It looks like thumbnail icons don't get updated. Only when a new image is added
4. Doing a full Zoom on a 256x256 image crashes the program and my VM. 

At this point I don't think it's very usable on linux

**Comment by rchastain** [comment]
Indeed when I try to change the zoom sometimes the application crashes. I looked into the code. I have an idea but I don't want to make you waste your time, so I will try it first on my side and if the result is good I will tell you.

Otherwise the application seems to work, and looks nice. (For me I removed the "Click me" panel, and changed to initial window state to "maximized".)

It is not easy to find the good formula with splitters, anchors, alignment options... It remembers me when I was working on this [little project](https://gitlab.com/rchastain/textview).

By the way, have you seen that I updated [MSPACMAN](https://forum.lazarus.freepascal.org/index.php/topic,54531.msg449041.html#msg449041)?

**Comment by RetroNick2020** [comment]
it looks like github did not add one of the replies from the email. I will add here
--------------------------------------------------------------------------------------
yes make whatever changes you like to make it work.

are you using the 32bit lazarus or 64 bit? it may be the same issue i faced on windows where creating huge canvas on 32bi caused crashing, on 64 bit works fine.

I have not seen the update for the mspacan. I will take a look. Good job with sticking to it.

**Comment by DualBrain** [comment]
This isn't entirely limited to linux (similar issue with a Window's laptop with maximum 768 lines); I've added issue #14 that is sort of related to this issue but with a lot more details/suggestion.

**Comment by RetroNick2020** [comment]
some changes made - please test

**Comment by rchastain** [comment]
Hello! Yes, it's better now. The palette is no longer hidden by the button, and I can resize the grid.

By the way, a small thing to fix: when I close the application through the menu File/Exit, the confirmation dialog shows twice: I have to click twice on "Yes".

**Comment by RetroNick2020** [comment]
ok - fixed exit menu.

**Comment by rchastain** [comment]
Thank you.

**Comment by RetroNick2020** [comment]
yes make whatever changes you like to make it work.

are you using the 32bit lazarus or 64 bit? it may be the same issue i faced
on windows where creating huge canvas on 32bi caused crashing, on 64 bit
works fine.

I have not seen the update for the mspacan. I will take a look. Good job
with sticking to it.
