### ISSUE TITLE
Palette is "off screen" and doesn't utilize region effectively.

### ISSUE THREAD

**Issue by DualBrain** [RetroNick2020/raster-master#14]
Really noticeable on my 9yo daughter's laptop (where she is primarily using this) that is limited to 1366x768 maximum screen dimension (running Windows 10).

It looks like the "zoom" component appears to take up a significant amount of screen real-estate; almost 1/3rd of the region pushing the palette "off screen".  Additionally, resizing the palette region doesn't cause the color swatch to resize - meaning not able to take advantage of the additional space.  If it could change to 3 columns (in this case) then all of the colors would be visible.

So if the "zoom" component were to be placed "elsewhere" (such as the center-upper region like it is in the map editor) and the color swatch placed at the top of the region that it is currently in, this would at least resolve the "off screen" issue... but it would (in my mind) make it easier to then take advantage of the width of the region by drawing the color swatch in more columns.

In any case, it might also make sense to have the color swatch contained within a scroll region.

**Comment by RetroNick2020** [comment]
yes this is something i am aware of. the palette component also changes size when using the 256 color palette.
Windows also has scale layout Desktop properties that can go up 175%.  I need to learn more about windows and Lazarus to figure out some of these problems.  I can wrap the palette component in a scroll box and anchor to right side of window and lower RM Panel. I need to test to see if this works or just breaks other features.

I am coming from a 30 year break from programming mostly in Turbo Pascal\QB DOS (hobby) to Windows so some of these problems that others have solved are new to me. I will figure things out though. I think i am passed the point now where i am fixing more things than i am breaking.

**Comment by RetroNick2020** [comment]
some changes made - please test

**Comment by DualBrain** [comment]
She can now access the two bottom colors of the 16-color swatch on her laptop. 👍
