### ISSUE TITLE
An interesting Turbo Pascal program, Baby Chess

### ISSUE THREAD

**Issue by rchastain** [RetroNick2020/raster-master#22]
Hello Nick. I hope you don't mind if I create this discussion here. I discovered a project that you could find interesting:

- [Baby Chess](https://github.com/evgeniykorniloff/baby-chess)

I started to port it to Free Pascal + ptcGraph, but I have no idea how to load the pictures. I said to myself that maybe you would accept to involve yourself in that little project.

I attach here the current state of my code. It compiles and starts, with pictures indexes displayed instead of pictures. Please see _uobj.pas_.

[baby-chess-ptcgraph-230518.zip](https://github.com/RetroNick2020/raster-master/files/11510434/baby-chess-ptcgraph-230518.zip)

(By the way there is [another interesting project](https://github.com/rchastain/pascal-russian-checkers) by the same author that I could easily port to FPC.)

Regards.

Roland

**Comment by RetroNick2020** [comment]
interesting timing - i have spent the last couple of months researching
various object formats and creating a few programs. take a look at rtBinObj
and rtBinSrc - feel free to fork and create linux versions if you find them
useful.

back to your problem. it looks like you need to convert the pic.obj to a
more cross platform format. it looks like its ega/vga screen dump

I'll take a look at your code and see if I can implement something to
display with ptcgraph.

I am always looking for some small games to play around with

**Comment by rchastain** [comment]
Thanks for your kind answer. Yes, I will take a look at rtBinObj and rtBinSrc.

See you!

**Comment by rchastain** [comment]
Meanwhile I found a temporary solution: I used graphics coming from another program. You can see the result [here](https://github.com/rchastain/baby-chess).

But I still would be interested in having the original pieces, if possible.

See you soon!

**Comment by rchastain** [comment]
I fixed memory leaks, so it's better to use the code of the repository instead of the code that I posted here.

If you compile with `make`, the program uses the replacement pictures.

If you compile with `make original`, the program uses the _uobj_ unit.

**Comment by RetroNick2020** [comment]
Hi Ronan,

I did a quick conversion of the pic.obj to a raw file. each byte
represents a pixel. the pieces are 50x50, I have included modified
code to display the pieces. this should get you back on track. you can
convert the raw file to a byte array so you don't have to allocate
memory or read it from disk. use the rtBinSrc program

**Comment by rchastain** [comment]
Hi Nick. Great news! But I think that you forgot to attach the files.

**Comment by RetroNick2020** [comment]
That's great! Use what ever works better for you.

[babychess.zip](https://github.com/RetroNick2020/raster-master/files/11512064/babychess.zip)

**Comment by RetroNick2020** [comment]
The new pieces look great! Unless you are trying to preserve the original I don't think you are losing anything.

**Comment by RetroNick2020** [comment]
if you decide to import the raw file to array using rtbinsrc set the items per line to 50. you will be able to see the chess pieces in text form.

**Comment by rchastain** [comment]
Thank you very much Nick! Your code works perfectly. I also tried rtBinSrc, and it works perfectly too. Finally I decided to remove commas from Pascal code generated by rtBinSrc and to use it as a simple text file.

It's true that the new pieces are nice but I am glad to have also the original pieces.

Now I can focus on the chess program itself.

**Comment by RetroNick2020** [comment]
That's great. What ever format works for you.
