### ISSUE TITLE
Raster Master couldn't build on Windows 11 and Pardus 21 (Debian 11 based, x86-64)

### ISSUE THREAD

**Issue by eersoy93** [RetroNick2020/raster-master#24]
Used Lazarus 2.2.6 with FreePascal 3.2.2. Used 64-bit software.

Raster Master commit number: [c011aa0](https://github.com/RetroNick2020/raster-master/commit/c011aa015bf61a49b8b1ee5c1b3aa18b31900756)

Thank you for your interest.

**Comment by RetroNick2020** [comment]
follow the video.  you need to install the ColorPalette package from the online package manager before compiling.
Sorry I don't test on Linux.

https://youtu.be/HfCiWIqQhTI

**Comment by eersoy93** [comment]
Lazarus says rmcolorxga.pas not found.

**Comment by RetroNick2020** [comment]
I have updated the missing file. you can clone or download the entire master or the missing file.

**Comment by eersoy93** [comment]
I have tried last revision on Windows 11. I'll try this on Pardus 21.

**Comment by RetroNick2020** [comment]
you may need to change some filenames to all lowercase. There was also an issue with the listview items last time i tried. good luck.

**Comment by eersoy93** [comment]
The project successfully built and run on Pardus 21 (Debian 11-based, x86-64).

**Comment by RetroNick2020** [comment]
that's great. I wasn't expecting that.
