### ISSUE TITLE
Very slow and expensive

### ISSUE THREAD

**Issue by GuvaCode** [RetroNick2020/raster-master#31]
- Primarily. It's a good project.
- I liked that you can draw shapes with tiles
- There are many formats

but the render needs to be done through something else. at 64x64, everything is bad
I haven't looked at the code. but if the rendering is very CPU intensive

**Comment by RetroNick2020** [comment]
is this on linux?

**Comment by GuvaCode** [comment]
Yes.

**Comment by RetroNick2020** [comment]
There a few issues I noticed on linux. The icons in the listview don't get updated unless there is a window activate/focus message. I occasionally compile on linux to make sure everything  still compiles but it seems everything runs much slower.

My original plan was just to do a Windows port of the original Turbo Pascal version.  Things kind of progressed where I managed to add a bunch of features. The code is a mess in many places. I'm amazed everything still works.

I don't know if there is much I can do to improve the performance on Linux. My knowledge of Linux is limited.

**Comment by RetroNick2020** [comment]
Update - I think I found the problem. its not the map drawing that is causing the issue. Its the updating of the thumbnail view for the maps. I have limited the thumbnail view to handle only the first 32x32 tiles now and that seems to make things work properly again.
