### ISSUE TITLE
Unit names case

### ISSUE THREAD

**Issue by rchastain** [RetroNick2020/raster-master#8]
Hello!

Just a word to say that I had to change _RMThumb.PAS_ to _RMThumb.pas_. Otherwise the compiler didn't find the unit. It's on Linux. Maybe it would be a good idea to normalize all file names.

Another detail. In the Tools menu, there is a missing letter in "Rectangle".

Regards.

Roland

**Comment by RetroNick2020** [comment]
Hi Roland, thanks for taking the time to download and compile on linux.

I will start renaming all the files to lowercase and fix the typo.

**Comment by RetroNick2020** [comment]
I have made the changes, if you are able test and see if everything compiles i would appreciate that.

btw did you ever finish the pacman port?

**Comment by rchastain** [comment]
Thank you for the changes. Yes, everything compiles now.

When I have time, I will play with the application to see what I could do with it.

No, I didn't retouch to PacMan, but maybe soon I will come back to that project. I will tell you.

I close the issue.

Regards.

Roland
